$(document).ready(function(){
    $('#mapButtonRight').on('click',function(){
       $('#content').toggleClass('swipeToLeft');
        //alert("Hello!");
    });
    /*$('body').on('swiperight',function(){
        $('ul').addClass('showMenu');
        $('.main').addClass('slideBody');
        $('.main').addClass('no-scroll');
        $('.shadow').fadeIn("fast","linear");
    });
    $('.shadow').on('click',function(){
        $('ul').toggleClass('showMenu');
        $('.main').toggleClass('slideBody');
        $('.main').toggleClass('no-scroll');
        $('.shadow').fadeToggle("fast","linear");
    });*/
    $('#body').on('swipeleft',function(){
        $(body).toggleClass('swipeToLeft');
    });
});